//
//  TextCell.swift
//  ImoCollectionView_Example
//
//  Created by Borinschi Ivan on 11/2/16.
//  Copyright (c) 2016 Imodeveloperlab. All rights reserved.
//
//  This file was generated by the ImoCollectionView Xcode Templates
//

import UIKit
import ImoCollectionView

extension UIFont {
    func sizeOfString (string: String, constrainedToWidth width: Double) -> CGSize {
        return (string as NSString).boundingRect(with: CGSize(width: width, height: DBL_MAX),
                                                 options: NSStringDrawingOptions.usesLineFragmentOrigin,
                                                 attributes: [NSFontAttributeName: self],
                                                 context: nil).size
    }
}

class TextCellSource: ImoCollectionViewCellSource {
    
    var text : String?
    var font : UIFont?
    
    public init(text: String) {
        
        self.text = text
        self.font = UIFont(name:"HelveticaNeue", size: 14)
        super.init(cellClass: "TextCell")
        
        let screenSize: CGRect = UIScreen.main.bounds
        self.width = screenSize.width
        
        if let font = self.font {
            
            let size = font.sizeOfString(string: self.text! , constrainedToWidth: Double(screenSize.width-30))
            self.height = size.height + 25
            
        }
        else {
            
            self.height = 100
        }
        
        self.nib = UINib(nibName: self.cellClass, bundle: Bundle.init(for: self.classForCoder))
    }
    
}


class TextCell: ImoCollectionViewCell {
    
    @IBOutlet weak var textLabel: UILabel!
    
    public override func setUpWithSource(source:AnyObject) {
        
        if source is TextCellSource {
            
            textLabel.text = source.text
            textLabel.font = source.font
        }
    }
}
