//
//  TitleHeaderView.swift
//  ImoCollectionView_Example
//
//  Created by Borinschi Ivan on 11/4/16.
//  Copyright (c) 2016 Imodeveloperlab. All rights reserved.
//
//  This file was generated by the ImoCollectionView Xcode Templates
//

import UIKit
import ImoCollectionView

class TitleHeaderViewSource: ImoCollectionReusableViewSource {
    
    var title : String?
    
    override init(headerWithHeight height: CGFloat) {

        super.init(headerWithHeight: height)
        self.viewClass = "TitleHeaderView"
        self.nib = UINib(nibName: self.viewClass, bundle: Bundle.init(for: self.classForCoder))
    }
}


class TitleHeaderView: ImoCollectionReusableView  {
   

    @IBOutlet weak var headerTitle: UILabel!
    
    override func setUpWithSource(source: AnyObject) {

        if source is TitleHeaderViewSource {
            
            if let _ = source.title {
                headerTitle.text = source.title
            }
            else
            {
                headerTitle.text = ""
            }
        }
    }
}

